[package]
name = "header-append-filter"
version = "0.1.1"
authors = ["Daniel Grimm <dgrimm@redhat.com>"]
edition = "2018"

[dependencies]
proxy-wasm = "0.1.3"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
